FROM ajardin/symfony-php:8.0-blackfire

LABEL org.opencontainers.image.authors="Alexandre Jardin <info@ajardin.fr>"
LABEL org.opencontainers.image.title="PHP 8.0 image with Blackfire for a Sylius application."
LABEL org.opencontainers.image.description="https://sylius.com/"
LABEL org.opencontainers.image.source="https://github.com/ajardin/docker-images/tree/master/sylius/php"

RUN docker-php-ext-install exif
