FROM ajardin/symfony-php:7.2

LABEL org.opencontainers.image.authors="Alexandre Jardin <info@ajardin.fr>"
LABEL org.opencontainers.image.title="PHP 7.2 image for a Drupal application."
LABEL org.opencontainers.image.description="https://www.drupal.org/"
LABEL org.opencontainers.image.source="https://github.com/ajardin/docker-images/tree/master/drupal/php"
