FROM ajardin/symfony-php:7.4

LABEL org.opencontainers.image.authors="Alexandre Jardin <info@ajardin.fr>"
LABEL org.opencontainers.image.title="PHP 7.4 image for a Sylius application."
LABEL org.opencontainers.image.description=""
LABEL org.opencontainers.image.source="https://github.com/ajardin/docker-images/blob/master/sylius/php/7.4/Dockerfile"

RUN docker-php-ext-install exif
