FROM alpine:latest

LABEL org.opencontainers.image.authors="Alexandre Jardin <info@ajardin.fr>"
LABEL org.opencontainers.image.title="Image with Yarn to manage JavaScript dependencies."
LABEL org.opencontainers.image.description=""
LABEL org.opencontainers.image.source="https://github.com/ajardin/docker-images/blob/master/common/yarn/Dockerfile"

RUN apk add --no-cache yarn

WORKDIR /app
